// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe99-1tKZLecPq3Q41n9AR6ckG9byPewc',
    appId: '1:440737084421:web:808f22941443fb5d42186c',
    messagingSenderId: '440737084421',
    projectId: 'projectpulse-eb75e',
    authDomain: 'projectpulse-eb75e.firebaseapp.com',
    storageBucket: 'projectpulse-eb75e.firebasestorage.app',
    measurementId: 'G-P3LBXZK7N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCla0xI5rD-gXGDa8-owcfSyH9_Xf4hz_s',
    appId: '1:440737084421:android:5a80090e4aa0d6ef42186c',
    messagingSenderId: '440737084421',
    projectId: 'projectpulse-eb75e',
    storageBucket: 'projectpulse-eb75e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwA39CTy-_dd2IiV_o5QHSBo8iyMkf4ZM',
    appId: '1:440737084421:ios:fc63044781fd01a042186c',
    messagingSenderId: '440737084421',
    projectId: 'projectpulse-eb75e',
    storageBucket: 'projectpulse-eb75e.firebasestorage.app',
    iosBundleId: 'com.example.projectPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwA39CTy-_dd2IiV_o5QHSBo8iyMkf4ZM',
    appId: '1:440737084421:ios:fc63044781fd01a042186c',
    messagingSenderId: '440737084421',
    projectId: 'projectpulse-eb75e',
    storageBucket: 'projectpulse-eb75e.firebasestorage.app',
    iosBundleId: 'com.example.projectPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe99-1tKZLecPq3Q41n9AR6ckG9byPewc',
    appId: '1:440737084421:web:82d055e5a41a225242186c',
    messagingSenderId: '440737084421',
    projectId: 'projectpulse-eb75e',
    authDomain: 'projectpulse-eb75e.firebaseapp.com',
    storageBucket: 'projectpulse-eb75e.firebasestorage.app',
    measurementId: 'G-BYX0HWSYFN',
  );
}
